# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fleet < Formula
  desc "Set up, run and supervise a fleet of coding agents against one GitHub repository"
  homepage "https://github.com/noelzappy/fleet"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/noelzappy/fleet/releases/download/v0.1.2/fleet_0.1.2_darwin_amd64.tar.gz"
      sha256 "e36d4a976069734839f82978bc8525ddc0fea14745d0e65a39eebf28090333e2"

      define_method(:install) do
        bin.install "fleet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/noelzappy/fleet/releases/download/v0.1.2/fleet_0.1.2_darwin_arm64.tar.gz"
      sha256 "304d40570a7258e215167d50c62eaa8bc639b81d61b1b48fca283817f060eb3e"

      define_method(:install) do
        bin.install "fleet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/noelzappy/fleet/releases/download/v0.1.2/fleet_0.1.2_linux_amd64.tar.gz"
      sha256 "f727822c618c6261f0dd9296a55e40f235fef5d5b0044b29ee69842e8c7abc14"
      define_method(:install) do
        bin.install "fleet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noelzappy/fleet/releases/download/v0.1.2/fleet_0.1.2_linux_arm64.tar.gz"
      sha256 "f68d24fa20453486415a8ffd452cd08cf98b1632b89c157a38183909786cff9c"
      define_method(:install) do
        bin.install "fleet"
      end
    end
  end

  test do
    assert_match "fleet", shell_output("#{bin}/fleet version")
  end
end
