# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fleet < Formula
  desc "Set up, run and supervise a fleet of coding agents against one GitHub repository"
  homepage "https://github.com/noelzappy/fleet"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/noelzappy/fleet/releases/download/v0.1.1/fleet_0.1.1_darwin_amd64.tar.gz"
      sha256 "831f9fb83eee3e6d0d870a64e494c513ddf7d3b6a317a5f7aa0651a2006cdd40"

      define_method(:install) do
        bin.install "fleet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/noelzappy/fleet/releases/download/v0.1.1/fleet_0.1.1_darwin_arm64.tar.gz"
      sha256 "ca15713c53c96aba64ce5f677cc9a5540f6c1c1a1d22bb054e90960e7cb36e0e"

      define_method(:install) do
        bin.install "fleet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/noelzappy/fleet/releases/download/v0.1.1/fleet_0.1.1_linux_amd64.tar.gz"
      sha256 "371ec4be7acbaac515c604c6ef0e86d851cc6508369ce290d0a7a3586afe35f6"
      define_method(:install) do
        bin.install "fleet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noelzappy/fleet/releases/download/v0.1.1/fleet_0.1.1_linux_arm64.tar.gz"
      sha256 "b72fde68d309e2864b7bdfe81aa8f785c4054ea2e2136d1cc0dcf723a2c08da7"
      define_method(:install) do
        bin.install "fleet"
      end
    end
  end

  test do
    assert_match "fleet", shell_output("#{bin}/fleet version")
  end
end
